name: Build Vue

on:
  workflow_run:
    workflows: ["cypress"]
    types:
      - completed

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue

    steps:
      - uses: actions/checkout@v2

      - name: Run Component test
        run: npm test

      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "iykeevans"
          reponame: "deezer-clone"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
